#!/usr/bin/env sh
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

JB_Apps='^(CLion|PyCharm|IntelliJ IDEA)$'

# bsp or float (default: bsp)
yabai -m config layout bsp

##abai -m signal --add event=space_changed action='~/.config/yabai/focus_space_window.sh $YABAI_SPACE_ID'
#yabai -m signal --add event=window_destroyed action='~/.config/yabai/window-focus-on-destroy.sh'
#yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq '.[1].id // .[0].jd' )"
#yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq 'map(select(.space == $YABAI_SPACE_ID))[1].id // map(select(.space == $YABAI_SPACE_ID))[0].id' --argjson YABAI_SPACE_ID \"$YABAI_SPACE_ID\")"
#yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq 'select(.space == $YABAI_SPACE_ID).id' --arg YABAI_SPACE_ID \"$YABAI_SPACE_ID\")"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m config external_bar all:39:0

yabai -m space 1 --label term
yabai -m space 2 --label code
yabai -m space 3 --label www
yabai -m space 4 --label chat
yabai -m space 5 --label todo
yabai -m space 6 --label music
yabai -m space 7 --label spare1
yabai -m space 8 --label spare2

#specific layout for chat space
# yabai -m config --space chat layout stack
# yabai -m config --space todo layout stack

#assign apps to certain space
yabai -m rule --add app="Microsoft Teams" space=chat
yabai -m rule --add app="Slack" space=chat
yabai -m rule --add app="Iterm2" space=term
yabai -m rule --add app="${JB_Apps}" title="^$" space=code
#yabai -m rule --add app="IntelliJ IDEA" space=code
#yabai -m rule --add app="IntelliJ IDEA" title=".*\[(.*)\].*" space=code
yabai -m rule --add app="Firefox" space=www
yabai -m rule --add app="Safari" space=www
yabai -m rule --add app="Arc" space=www
yabai -m rule --add app="Chrome" space=www
yabai -m rule --add app="Spotify" space=music
yabai -m rule --add app="Microsoft To Do" space=todo
yabai -m rule --add app="Signal" space=chat
yabai -m rule --add app="Logseq" space=todo
yabai -m rule --add app="Discord" space=chat
yabai -m rule --add app="Calendar" space=todo
yabai -m rule --add app="Notion" space=todo
yabai -m rule --add app="Notes" space=todo
yabai -m rule --add app="^Outlook$" space=todo
yabai -m rule --add app="^OneNote$" space=todo
yabai -m rule --add app="^Todoist$" space=todo
yabai -m rule --add app="Reminders" space=todo
#yabai -m rule --add app="Sharing Indicator" manage=off

#yabai -m rule --add subrole="AXDialog" layer=above manage=off
# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="${JB_Apps}" manage=off
# If `Open last project when launch` is checked, add this rule. And make sure `always show project path` is also checked.
yabai -m rule --add app="${JB_Apps}" title=".*\[.*\].*" manage=on
yabai -m rule --add app="${JB_Apps}" title="^$" manage=on
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off
yabai -m rule --add app="Prusa Slicer" manage=off
yabai -m rule --add app="^Parallels Desktop$" manage=off
yabai -m rule --add app="Karabiner-Elements" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^TeamViewer$" manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
#yabai -m rule --add title="Microsoft Teams Notification"
#yabai -m rule --add app="^Spotify$" manage=off
#yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Age of Empires$" manage=off
yabai -m rule --add app="^Hammerspoon$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^perl_client_app$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^CiscoSparkHelper$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Cisco Webex Start$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off

## Some random global settings
#yabai -m config focus_follows_mouse          autofocus
#yabai -m config focus_follows_mouse          on
# yabai -m config mouse_follows_focus           on
# New window spawns to the right if vertical split, or bottom if horizontal split
#yabai -m config window_placement second_child
#yabai -m config window_topmost off
#yabai -m config window_shadow float
#yabai -m config window_opacity off
yabai -m config window_shadow off
yabai -m config window_opacity_duration 0.00
#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity 0.9
#yabai -m config normal_window_opacity        0.97
#yabai -m config window_border                on | off

## WITH SIP ENABLED (Installed Limelight seperately, Don't need this)
#yabai -m config window_border off

## WTIH SIP DISABLED (Limelight build into Yabai, enable it here)
#yabai -m config window_border on
#yabai -m config window_border_width 2
#yabai -m config active_window_border_color 0xFF40FF00
#yabai -m config normal_window_border_color 0x00FFFFFF
#yabai -m config insert_feedback_color        0xffd75f5f

## some other settings
yabai -m config auto_balance off
#yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

## Change how yabai looks
yabai -m config top_padding 3
yabai -m config bottom_padding 3
yabai -m config left_padding 30
yabai -m config right_padding 3
yabai -m config window_gap 10

## If I close the active window, focus on any other visible window.
#yabai -m signal --add event=window_destroyed action="bash /Users/jesseskelton/CustomScripts/SwitchSpaces/window-focus-on-destroy.sh"
# yabai -m signal --add event=space_changed action="export CUR_ACTIVE_APP=\"iTerm2\""
#
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 2>/dev/null 1>&2 &

echo "yabai configuration loaded.."

#END
