format = """
($hostname)\
($git_branch)\
($git_status)\
$c\
$golang\
$java\
$nodejs\
$rust 
$env_var@$directory \
($cmd_duration) $status 
"""

right_format = """
$kubernetes\
"""

[directory]
# style = "fg:#abb2bf"
style = "fg:#c9d1d9"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"work" = "󰃖"
"code" = "󰈮"

[c]
symbol = " "
# style = "bg:#61afef"
style = "bg:#58a6ff"
format = '[$symbol ($version)]($style)'

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[env_var.ZVM_MODE]
format = "[$env_value]($style)"
style = 'green italic'

[env_var.USER]
format = "[$env_value]($style)"
# style = '#c678dd italic'
style = '#bc8cff italic'

[git_branch]
symbol = ""
format = '[$symbol $branch]($style)'

[git_status]
format = '[($all_status$ahead_behind )]($style)'

[golang]
symbol = " "

[java]
symbol = " "
format = '[$symbol ($version)]($style)'

[nodejs]
symbol = ""
format = '[$symbol ($version)]($style)'

[rust]
symbol = ""
format = '[$symbol ($version)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# style = "bg:#61afef"
style = "bg:#1f6feb"
# format = '[[ ♥ $time ](bg:#61afef) ]($style)'
format = '[[ ♥ $time ](bg:#1f6feb) ]($style)'

[kubernetes]
format = '[ ⛵ $context\($namespace\)]($style)'
disabled = false
# style="#61afef"
style="#58a6ff"
[kubernetes.context_aliases]
"dev-mips-ql" = "mips"
"minikube" = "mk"
"dev-meps" = "meps"

[kotlin]
disabled = false

[status]
map_symbol = true
# style = "fg:#98c379"
style = "fg:#58a6ff"
success_symbol = " "
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
disabled = false

[cmd_duration]
min_time = 500
format = '[$duration](bold yellow)'
