format = """
[](#9A348E)\
$directory\
[](fg:#9A348E bg:red)\
$kubernetes\
[](bg:#DA627D fg:red)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$c\
$golang\
$java\
$nodejs\
$rust\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A) \n \
❯
"""

[directory]
style = "bg:#9A348E"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'


[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[[ $symbol $branch ](bg:#FCA17D)]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[[($all_status$ahead_behind )](bg:#FCA17D)]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A) ]($style)'

[kubernetes]
format = '[[ ⛵ $context \($namespace\) ](bg:red)]($style)'
disabled = false
style="bg:red"
[kubernetes.context_aliases]
"dev-mips-ql" = "mips"
"minikube" = "mk"
"dev-meps" = "meps"

[kotlin]
disabled = false

