format = """
$directory\
$git_branch\
$git_status\
$c\
$golang\
$java\
$nodejs\
$rust \n
❯
"""

right_format = """
$kubernetes\
"""

[directory]
style = "fg:green"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"work" = "󰃖"
"code" = "󰈮"

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[($all_status$ahead_behind )]($style)'

[golang]
symbol = " "

[java]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
format = '[ $symbol ($version)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A) ]($style)'

[kubernetes]
format = '[ ⛵ $context\($namespace\)]($style)'
disabled = false
style="white"
[kubernetes.context_aliases]
"dev-mips-ql" = "mips"
"minikube" = "mk"
"dev-meps" = "meps"

[kotlin]
disabled = false

