---
brew_taps:
  - anomalyco/tap
  - azure/kubelogin
  - breuerfelix/tap
  - cjsaylor/tap
  - derailed/popeye
  - deviceinsight/packages
  - felixkratz/formulae
  - fluxcd/tap
  - graalvm/tap
  - hashicorp/tap
  - homebrew/bundle
  - homebrew/services
  - kardolus/chatgpt-cli
  - keith/formulae
  - koekeishiya/formulae
  - lencx/chatgpt
  - nikitabobko/tap
  - notwadegrimridge/brew
  - osx-cross/arm
  - osx-cross/avr
  - oven-sh/bun
  - qmk/qmk
  - sachaos/todoist
  - shopify/shopify
  - surrealdb/tap
  - ynqa/tap

brew_formulae:
  - act
  - anomalyco/tap/opencode
  - ansible
  - ant
  - aria2
  - atuin
  - awscli
  - azure-cli
  - azure/kubelogin/kubelogin
  - bandwhich
  - bat
  - bitwarden-cli
  - bpytop
  - cabextract
  - carapace
  - chezmoi
  - cjsaylor/tap/jrnl
  - clusterctl
  - cmake
  - code-server
  - commitizen
  - coreutils
  - ctop
  - cypher-shell
  - delve
  - derailed/popeye/popeye
  - dive
  - docker-compose
  - dog
  - dos2unix
  - dua-cli
  - duf
  - exiftool
  - eza
  - fd
  - felixkratz/formulae/borders
  - felixkratz/formulae/sketchybar
  - felixkratz/formulae/svim
  - ffmpeg@4
  - ffmpegthumbnailer
  - fluxcd/tap/flux
  - gemini-cli
  - gh
  - ghostscript
  - git-filter-repo
  - git-lfs
  - gitui
  - glab
  - glances
  - gnu-sed
  - gobject-introspection
  - golangci-lint
  - golangci-lint-langserver
  - gomplate
  - gopls
  - gping
  - gradle
  - grep
  - groonga
  - hashicorp/tap/packer
  - hashicorp/tap/terraform
  - hashicorp/tap/terraform-ls
  - hashicorp/tap/vault
  - hcloud
  - helix
  - helmfile
  - htop
  - hugo
  - ifstat
  - imagemagick
  - jj
  - jq
  - jsonnet
  - just
  - k3d
  - k9s
  - kafka
  - kafkactl
  - kardolus/chatgpt-cli/chatgpt-cli
  - keith/formulae/reminders-cli
  - kind
  - koekeishiya/formulae/skhd
  - koekeishiya/formulae/yabai
  - kotlin
  - ktlint
  - kube-bench
  - kubebuilder
  - lastpass-cli
  - lazygit
  - libraw
  - librealsense
  - librespot
  - llvm
  - lsd
  - luarocks
  - marksman
  - mas
  - maven
  - mcp-proxy
  - meson
  - minikube
  - mkcert
  - molten-vk
  - mosquitto
  - navi
  - ncdu
  - neovim
  - newsboat
  - nowplaying-cli
  - nushell
  - ollama
  - openconnect
  - opencv
  - openjdk@11
  - openjdk@17
  - openshift-cli
  - openstackclient
  - opentofu
  - oven-sh/bun/bun
  - pass
  - pgloader
  - pint
  - pipx
  - pnpm
  - poppler
  - powershell
  - prettier
  - pulumi
  - putty
  - python@3.11
  - python@3.9
  - qmk/qmk/qmk
  - qt@5
  - rainfrog
  - rm-improved
  - rustup
  - s3cmd
  - sachaos/todoist/todoist
  - sevenzip
  - shopify/shopify/shopify-cli
  - snapcast
  - sops
  - sshuttle
  - starship
  - surrealdb/tap/surreal
  - switchaudio-osx
  - sysdig
  - tailscale
  - talisman
  - telnet
  - thefuck
  - unar
  - vim
  - watson
  - wget
  - wimlib
  - yaml-language-server
  - yarn
  - yazi
  - ynqa/tap/jnv
  - yq
  - zellij
  - zoxide

brew_casks:
  - aerospace
  - anaconda
  - bambu-studio
  - bluetility
  - brave-browser
  - chatgpt
  - claude-code
  - cmake
  - cmake-app
  - codex
  - discord
  - displaylink
  - elgato-stream-deck
  - figma
  - firefox
  - firefox-developer-edition
  - firefox@developer-edition
  - font-hack-nerd-font
  - font-jetbrains-mono
  - font-monaspace
  - font-sf-mono
  - font-sf-pro
  - font-symbols-only-nerd-font
  - ghostty
  - graalvm-community-jdk21
  - homerow
  - jetbrains-toolbox
  - keystore-explorer
  - maccy
  - meetingbar
  - microsoft-auto-update
  - microsoft-teams
  - ngrok
  - obsidian
  - pingplace
  - postman
  - powershell
  - proton-mail-bridge
  - protonmail-bridge
  - raycast
  - rustdesk
  - sf-symbols
  - signal
  - sketchup
  - slack
  - spotify
  - spurwechsel
  - tailscale-app
  - teamviewer
  - todoist
  - todoist-app
  - tunnelblick
  - visual-studio-code
  - vlc
  - wezterm@nightly
  - whatsapp
  - windows-app
  - yubico-authenticator
  - zoom
  - zulu
  - zulu17
  - zulu21
  - zulu@17
  - zulu@21

mas_apps:
  - { id: 948660805, name: "AusweisApp" }
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 1193539993, name: "Brother iPrint&Scan" }
  - { id: 682658836, name: "GarageBand" }
  - { id: 409183694, name: "Keynote" }
  - { id: 1274495053, name: "Microsoft To Do" }
  - { id: 409203825, name: "Numbers" }
  - { id: 823766827, name: "OneDrive 2" }
  - { id: 409201541, name: "Pages" }
  - { id: 1310584536, name: "Planner 5D" }
  - { id: 669289700, name: "Sweet Home 3D" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 1295203466, name: "Windows App 2" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 497799835, name: "Xcode" }
